version: '3.4'
services:
  devfreelapi:
    image: ${DOCKER_REGISTRY-}devfreelapai
    container_name: apiaspn
    build:
      context: .
      dockerfile: DevFreela.Api/Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - db-volume:/var/lib/postgres/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: apidevfreela
volumes:
  db-volume:
